# -*- coding: utf-8 -*-
"""功能模块

包含基础参数、经济参数、控制策略、仿真计算、可视化等核心功能模块
"""

from .basic_params import (
    get_bess_params,
    set_bess_params,
    validate_bess_params,
    reset_to_default as reset_bess_to_default,
    create_basic_params_tab,
    setup_basic_params_events,
)

from .economic_params import (
    get_economic_params,
    set_economic_params,
    validate_economic_params,
    reset_to_default as reset_economic_to_default,
    calculate_peak_valley_spread,
    calculate_initial_investment,
    calculate_full_economics,
    create_economic_params_tab,
    setup_economic_params_events,
)

from .control_params import (
    get_control_params,
    set_control_params,
    validate_control_params,
    reset_to_default as reset_control_to_default,
    generate_dispatch_schedule,
    create_control_params_tab,
    setup_control_params_events,
)

from .simulation import (
    run_simulation,
    get_load_profile,
    load_custom_profile,
    calculate_statistics,
    calculate_annual_projection,
    plot_simulation_results,
    format_statistics_table,
    format_annual_table,
    create_simulation_tab,
    setup_simulation_events,
)

from .visualization import (
    ChartStyle,
    ChartLibrary,
    ExportConfig,
    plot_power_curve,
    plot_soc_curve,
    plot_energy_summary,
    generate_statistics_table,
    generate_annual_table,
    export_results,
    plot_combined_dashboard,
    VISUALIZATION_TEACHING_META,
)

from .learning_center import (
    KnowledgeLevel,
    KnowledgePoint,
    Terminology,
    get_knowledge_tree,
    get_terminology_dict,
    get_knowledge_point,
    search_knowledge,
    search_terminology,
    get_param_help,
    create_learning_center_tab,
    setup_learning_center_events,
    LEARNING_TEACHING_META,
)

from .ems_architecture import (
    ComponentType,
    EMSState,
    SystemComponent,
    Connection,
    SystemTopology,
    StateTransition,
    StateMachine,
    ModbusRegister,
    ModbusProtocol,
    get_system_topology,
    get_state_machine,
    get_modbus_protocol,
    get_component_detail,
    render_topology_diagram,
    render_state_machine_diagram,
    get_register_table_data,
    get_data_flow_table,
    create_ems_architecture_tab,
    setup_ems_architecture_events,
    EMS_ARCHITECTURE_TEACHING_META,
)

from .fault_diagnosis import (
    FaultCategory,
    FaultSeverity,
    FaultStatus,
    FaultType,
    FaultInstance,
    AlarmRecord,
    DiagnosisStep,
    DiagnosisGuide,
    FaultCase,
    get_fault_types,
    get_fault_type,
    get_diagnosis_guides,
    get_diagnosis_guide,
    get_fault_cases,
    get_fault_case,
    inject_fault,
    clear_fault,
    clear_all_faults,
    get_active_faults,
    get_alarm_records,
    acknowledge_alarm,
    create_fault_diagnosis_tab,
    setup_fault_diagnosis_events,
    FAULT_DIAGNOSIS_TEACHING_META,
)

__all__ = [
    # Basic params
    'get_bess_params',
    'set_bess_params',
    'validate_bess_params',
    'reset_bess_to_default',
    'create_basic_params_tab',
    'setup_basic_params_events',
    # Economic params
    'get_economic_params',
    'set_economic_params',
    'validate_economic_params',
    'reset_economic_to_default',
    'calculate_peak_valley_spread',
    'calculate_initial_investment',
    'calculate_full_economics',
    'create_economic_params_tab',
    'setup_economic_params_events',
    # Control params
    'get_control_params',
    'set_control_params',
    'validate_control_params',
    'reset_control_to_default',
    'generate_dispatch_schedule',
    'create_control_params_tab',
    'setup_control_params_events',
    # Simulation
    'run_simulation',
    'get_load_profile',
    'load_custom_profile',
    'calculate_statistics',
    'calculate_annual_projection',
    'plot_simulation_results',
    'format_statistics_table',
    'format_annual_table',
    'create_simulation_tab',
    'setup_simulation_events',
    # Visualization
    'ChartStyle',
    'ChartLibrary',
    'ExportConfig',
    'plot_power_curve',
    'plot_soc_curve',
    'plot_energy_summary',
    'generate_statistics_table',
    'generate_annual_table',
    'export_results',
    'plot_combined_dashboard',
    'VISUALIZATION_TEACHING_META',
    # Learning Center
    'KnowledgeLevel',
    'KnowledgePoint',
    'Terminology',
    'get_knowledge_tree',
    'get_terminology_dict',
    'get_knowledge_point',
    'search_knowledge',
    'search_terminology',
    'get_param_help',
    'create_learning_center_tab',
    'setup_learning_center_events',
    'LEARNING_TEACHING_META',
    # EMS Architecture
    'ComponentType',
    'EMSState',
    'SystemComponent',
    'Connection',
    'SystemTopology',
    'StateTransition',
    'StateMachine',
    'ModbusRegister',
    'ModbusProtocol',
    'get_system_topology',
    'get_state_machine',
    'get_modbus_protocol',
    'get_component_detail',
    'render_topology_diagram',
    'render_state_machine_diagram',
    'get_register_table_data',
    'get_data_flow_table',
    'create_ems_architecture_tab',
    'setup_ems_architecture_events',
    'EMS_ARCHITECTURE_TEACHING_META',
    # Fault Diagnosis
    'FaultCategory',
    'FaultSeverity',
    'FaultStatus',
    'FaultType',
    'FaultInstance',
    'AlarmRecord',
    'DiagnosisStep',
    'DiagnosisGuide',
    'FaultCase',
    'get_fault_types',
    'get_fault_type',
    'get_diagnosis_guides',
    'get_diagnosis_guide',
    'get_fault_cases',
    'get_fault_case',
    'inject_fault',
    'clear_fault',
    'clear_all_faults',
    'get_active_faults',
    'get_alarm_records',
    'acknowledge_alarm',
    'create_fault_diagnosis_tab',
    'setup_fault_diagnosis_events',
    'FAULT_DIAGNOSIS_TEACHING_META',
]
